### ISSUE TITLE
pulling details for movies with the same name

### ISSUE THREAD

**Issue by liam-clifford** [preritdas/rottentomatoes-python#4]
I was playing around with your code in python and noticed an `TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'` error when using your movie class for Titles where there were multiple movies (Examples: Crash, Rush, Bad Boys).

Here's some code that should reproduce what exactly i'm seeing on my side:

```
import rottentomatoes as rt
movie = rt.Movie('Bad Boys')
```

I think this might be due to the fact the title argument is doing a literal text search against rotten tomatoes' database, maybe? In the scenario when you search for a Title that's related to multiple movies, it looks like it's failing perhaps because rotten-tomatoes has added a unique identifier to each movie url. Example:
- https://www.rottentomatoes.com/m/bad_boys_1982
- https://www.rottentomatoes.com/m/1062483-bad_boys

Not sure if this is a bug or not, but figured I'd flag it just in case!

**Comment by preritdas** [comment]
Ah, thanks for pointing this out. I'll look into it and get back to you.

**Comment by preritdas** [comment]
> I think this might be due to the fact the title argument is doing a literal text search against rotten tomatoes' database, maybe? In the scenario when you search for a Title that's related to multiple movies, it looks like it's failing perhaps because rotten-tomatoes has added a unique identifier to each movie url. Example:
> 
> - https://www.rottentomatoes.com/m/bad_boys_1982
> 
> - https://www.rottentomatoes.com/m/1062483-bad_boys

You're right. This has always been one of the biggest limitations. With an API we can query for movies, but when scraping it's a lot more difficult. Under the hood, we take the movie query name and reformat it to fit in the traditional Rotten Tomatoes URL format. But you're exactly right in that many movies have unique identifiers, or a year before the name, or something else to distinguish them from a similar titled movie. 

The solution to this problem in my eyes is to replace the function that constructs a movie url with a search page scraping mechanism. 

Ex. for Bad Boys, scrape the page `https://www.rottentomatoes.com/search?search=Bad%20boys`. Then we can pull the movie url of the top movie _that has a Tomatometer_. Interestingly they've already put up the listing for Bad Boys for in 2024 which is returned before the 2020 film. 

This could be a bit of a project but should almost entirely solve the problem. Also, would be good to add in a raw search mechanism that maintains the current URL-building method so users can still access listings of specific movies directly. 

It may take me a little while to get to this as I'm preoccupied with a lot, so if you (or anyone else) want to give it a shot and open a PR I'd be happy to help however I can.

**Comment by preritdas** [comment]
I've implemented this in a branch and opened PR #5. Will be writing more docs, running some tests, and then hopefully merging. In the meantime you or anyone can clone the repo on that branch and test it.

**Comment by preritdas** [comment]
@liam-clifford Done! Published to PyPI as well.

**Comment by liam-clifford** [comment]
Hey, thanks for taking the time to look into this! I unfortunately don’t have the software development skills to patch this (otherwise I totally would love to help).Whether it be you or anyone else here, there’s zero rush from my side. I more so just wanted to point it out. What you’ve put together solves a good majority of what I wanted (the only thing that would be neat to have added is the number of critic and audience reviewers, but I’m not sure if that’s an easy add or not).In any case, thanks again for all of the work with this project!LiamOn Feb 12, 2023, at 12:53 PM, Prerit Das ***@***.***> wrote:﻿
I've implemented this in a branch and opened PR #5. Will be writing more docs, running some tests, and then hopefully merging. In the meantime you or anyone can clone the repo on that branch and test it.

**Comment by liam-clifford** [comment]
@preritdas just realized that I replied without seeing your most recent reply. Thanks for the quick fix!

To confirm, when I search "bad boys", the original error is no longer there. The movie result I get back is for the 2020 "Bad Boys" film (ie. https://www.rottentomatoes.com/m/bad_boys). 

Just to clarify: If I wanted to get the 1995 "bad boys" film, is the expected behavior to search essentially what's in the URL for that film? (ie. https://www.rottentomatoes.com/m/1062483-bad_boys) -- which would be "1062483 bad boys"?

Thanks again!

**Comment by preritdas** [comment]
Right now, default querying will return the first match that is a movie and has a tomatometer. So when you search [this](https://www.rottentomatoes.com/search?search=bad%20boys), you'll get the 2020 one because 2024 has no tomatometer. The problem is even when you search for "1995 bad boys" the results are still the same. Don't know why, their search mechanism must just suck. 

Right now my quick fix can only give the first valid movie response. In code, you can get the 1995 bad boys by querying with `raw_url = True`. This is not a great option though...

https://github.com/preritdas/rottentomatoes-python/blob/a8dffa067388740421cab3ea484a3ecfeeda6193/rottentomatoes/standalone.py#L89-L104

I'll try to implement a way to choose from the results. Thankfully it won't be too hard, because instead of a "quick fix" I actually structured the search mechanism with a `SearchListing` class and various helper functions.

https://github.com/preritdas/rottentomatoes-python/blob/a8dffa067388740421cab3ea484a3ecfeeda6193/rottentomatoes/search.py#L10-L44

It's just a matter of at what point do you choose from the available options... And how. Need to think about that, let me know if you have thoughts. 

You can use the [search](https://github.com/preritdas/rottentomatoes-python/blob/master/rottentomatoes/search.py) module's `search_results` function to get a list of `SearchListing` objects that you can sift through, but you'll have to do that manually. 

https://github.com/preritdas/rottentomatoes-python/blob/a8dffa067388740421cab3ea484a3ecfeeda6193/rottentomatoes/search.py#L58-L62

Let me know what you think... @liam-clifford

**Comment by preritdas** [comment]
Alright, I've got an interesting solution for now! Created an API. It's bare bones but does the job. Funny that we're creating an API that simulates the result of an API they already have but won't release.

The API isn't deployed anywhere (for now) but you can run it locally (I'll provide steps if you'd like). But it has two endpoints, `/movie/{movie_name}` and `/search/{movie_name}`. The first will pull one movie, the top result. The second will pull a list of _all_ valid movie results.

The first, with `movie_name="bad boys"`:

```json
{
  "name": "Bad Boys for Life",
  "tomatometer": 76,
  "audience_score": 96,
  "weighted_score": 82,
  "genres": [
    "Action",
    "Comedy"
  ],
  "rating": "R",
  "duration": "2h 4m",
  "year": "2020",
  "actors": [
    "Will Smith",
    "Martin Lawrence",
    "Vanessa Hudgens",
    "Jacob Scipio",
    "Alexander Ludwig"
  ],
  "directors": [
    "Adil El Arbi",
    "Bilall Fallah"
  ]
}
```

The second, with `movie_name="bad boys"`:

```json
{
  "movies": [
    {
      "name": "Bad Boys for Life",
      "tomatometer": 76,
      "audience_score": 96,
      "weighted_score": 82,
      "genres": [
        "Action",
        "Comedy"
      ],
      "rating": "R",
      "duration": "2h 4m",
      "year": "2020",
      "actors": [
        "Will Smith",
        "Martin Lawrence",
        "Vanessa Hudgens",
        "Jacob Scipio",
        "Alexander Ludwig"
      ],
      "directors": [
        "Adil El Arbi",
        "Bilall Fallah"
      ]
    },
    {
      "name": "Bad Boys II",
      "tomatometer": 23,
      "audience_score": 78,
      "weighted_score": 41,
      "genres": [
        "Action",
        "Comedy"
      ],
      "rating": "R",
      "duration": "2h 26m",
      "year": "2003",
      "actors": [
        "Martin Lawrence",
        "Will Smith",
        "Jordi Mollà",
        "Gabrielle Union",
        "Peter Stormare"
      ],
      "directors": [
        "Michael Bay"
      ]
    },
    {
      "name": "Bad Boys",
      "tomatometer": 43,
      "audience_score": 78,
      "weighted_score": 54,
      "genres": [
        "Action",
        "Comedy"
      ],
      "rating": "R",
      "duration": "1h 58m",
      "year": "1995",
      "actors": [
        "Martin Lawrence",
        "Will Smith",
        "Téa Leoni",
        "Tchéky Karyo",
        "Theresa Randle"
      ],
      "directors": [
        "Michael Bay"
      ]
    },
    {
      "name": "Bad Boys",
      "tomatometer": 90,
      "audience_score": 82,
      "weighted_score": 87,
      "genres": [
        "Drama"
      ],
      "rating": "R",
      "duration": "2h 3m",
      "year": "1983",
      "actors": [
        "Sean Penn",
        "Reni Santoni",
        "Esai Morales",
        "Jim Moody",
        "Ally Sheedy"
      ],
      "directors": [
        "Rick Rosenthal 2"
      ]
    }
  ]
}
```

When deployed you can do this in the browser too...

`http(s)://localhostordeployment/movie/bad_boys` for JSON response of the top result, or `http(s)://localhostordeployment/search/bad_boys` for a JSON response of all valid results.

I'm thinking of deploying this live somewhere, probably App Engine. Need to make sure Rotten Tomatoes doesn't come after me though! ;)

**Comment by preritdas** [comment]
I've deployed the API... The root endpoint is https://rotten-tomatoes-api.ue.r.appspot.com/. You can use /docs and /redoc to see endpoints and test them in the browser. 

- https://rotten-tomatoes-api.ue.r.appspot.com/movie/bad_boys for JSON response of the top result
- https://rotten-tomatoes-api.ue.r.appspot.com/search/bad_boys for a JSON response of all valid results.
